### ISSUE TITLE
KeyError: 'japan'

### ISSUE THREAD

**Issue by puckk** [Stiggu/agp-py#1]
Hello! Excellent work, but I have an error when I try to parse this hex: 0x100800000d2873430421284a044110440441188404a108480461204604612046:

```
Traceback (most recent call last):
  File "search.py", line 36, in search_axies
    gen = AxieGene("0x100800000d2873430421284a044110440441188404a108480461204604612046", 256)
  File "agp_py/main.py", line 17, in __init__
  File "agp_py/main.py", line 70, in axie_gene_from_binary
  File "agp_py/main.py", line 118, in parse_part
  File "agp_py/main.py", line 162, in find_part
KeyError: 'japan'
```

**Comment by Stiggu** [comment]
Just fixed this in d1e6d87 and updated the Pypi package, thank you for letting me know about the issue!
